version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_learning_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=ai-learning-assistant-prakash.duckdns.org
    container_name: ai_learning_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: ai_learning_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    restart: always

  grafana:
    image: grafana/grafana:10.0.3
    container_name: ai_learning_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always

volumes:
  uploads_data:
