apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-learning-assistant.fullname" . }}-frontend
  labels:
    {{- include "ai-learning-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "ai-learning-assistant.selectorLabels" . | nindent 4 }}
    app: {{ include "ai-learning-assistant.name" . }}-frontend
