apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-learning-assistant.fullname" . }}-uploads-pvc
  labels:
    {{- include "ai-learning-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize | quote }}
