apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-learning-assistant.fullname" . }}-secrets
  labels:
    {{- include "ai-learning-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodbUri | b64enc | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
